---
# This playbook deploys jenkins server and runs checkbox.io application

- name: Install and configure jenkins and run checkbox.io application
  hosts: production
  gather_facts: False
  become: yes
  become_user: root
  remote_user: root
  environment:
    MONGOUSER: "{{lookup('env', 'MONGOUSER')}}"
    MONGOPWD: "{{lookup('env', 'MONGOPWD')}}"
    SMTPEMAIL: "{{lookup('env', 'SMTPEMAIL')}}"
    SMTPPWD: "{{lookup('env', 'SMTPPWD')}}"
  roles:
    #- install_dependencies 
    - deploy_checkbox
