---
    # - name: install python 2
    #   raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      
    - name: Install required packages for build in the VM 
      apt: name={{ item }} state=present
      with_items:
       - maven
       - git

    - name: apt update
      become_user: root
      command: sudo apt-get update

    - name: Install dependencies
      apt: name={{ item }} state=present
      with_items: "{{ dependencies }}"
